; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Монитор порта
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; Пути для поиска библиотек
lib_extra_dirs = C:/Arduino/libraries

; Зависимости (библиотеки)
lib_deps = 
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    bblanchon/ArduinoJson

; Флаги компиляции
build_flags = 
    -std=gnu++17
    -Os
    -Isrc
    -DCONFIG_TASK_WDT_TIMEOUT_S=30
    -DCONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0=0

; Флаги для отключения
build_unflags = 
    -std=gnu++11